huggingface:
  model: "meta-llama/Llama-2-7b-chat-hf"
  revision: "f5db02db724555f92da89c216ac04704f23d4590"
  tensors: true
pipeline:
  name: "accelerate-llama2-7b-ft"
  version: "v1"
  image: '763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.2.0-gpu-py310-cu121-ubuntu20.04-sagemaker'
  steps:
    - name: finetune
      description: "fine tune model"
      config: finetune.yaml